# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: wineyard

ingress:
  - name: ingress
    bindings:
      - port: 8090
    rules:
      - path: /v6
        service: wineyard-api-6
      - path: /v7
        service: wineyard-api-7

services:
- name: wineyard-db
  image: postgres:11.17-alpine
  env:
    - name: POSTGRES_USER
      value: wineyard-dbuser
    - name: POSTGRES_PASSWORD
      value: password
    - name: POSTGRES_DB
      value: wineyard-db
  bindings:
    - port: 54321
      containerPort: 5432
      connectionString: Server=${host};Port=${port};Database=${env:POSTGRES_DB};User Id=${env:POSTGRES_USER};Password=${env:POSTGRES_PASSWORD};
- name: wineyard-api-6
  project: Wineyard.Api.6/Wineyard.Api.6.csproj
- name: wineyard-api-7
  project: Wineyard.Api.7/Wineyard.Api.7.csproj
- name: wineyard-tools
  project: Wineyard.Tools/Wineyard.Tools.csproj
