name: Docker Image CI by parallel jobs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    strategy:
      matrix:
        os: ['${{vars.X64_HOSTNAME}}','${{vars.ARM64_HOSTNAME}}']
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.2.0
      with:
        context: src/
        # Path to the Dockerfile
        file: src/Wineyard.Api.7/Dockerfile
        # List of metadata for an image
        labels: murilobeltrame/wineyard-api
        tags: 7
