name: Docker Image CI by parallel jobs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] 

jobs:

  build:

    strategy:
      matrix:
        platform: ['X64','ARM64']
  
    runs-on: ['self-hosted', 'linux', '${{matrix.platform}}'] 
  
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.2.0
      with:
        context: src/
        # Path to the Dockerfile
        file: src/Wineyard.Api.7/Dockerfile
        # Push is a shorthand for --output=type=registry
        push: true
        # List of tags
        tags: murilobeltrame/wineyard-api:7-${{matrix.platform}}
